### ISSUE TITLE
OOM in ASR Finetuning

### ISSUE THREAD

**Issue by QuyAnh2005** [QwenLM/Qwen3-ASR#91]
### Description

I am training on ~45k audio clips (≤30s each) using an A40 48GB GPU, but an OOM error occurs after 200 steps, even with batch size 8 and gradient accumulation 2 with `Qwen3-ASR-0.6B`.

### Reproduction

```
python qwen3_asr_sft.py \
  --model_path Qwen/Qwen3-ASR-0.6B \
  --train_file tamil_train.jsonl \
  --output_dir ./qwen3-asr-finetuning-out \
  --batch_size 8 \
  --grad_acc 2 \
  --gradient_checkpointing 1 \
  --lr 2e-5 \
  --epochs 3 \
  --save_steps 200 \
  --save_total_limit 5 \
  --wandb_project qwen3-asr-tamil \
  --wandb_run_name "tamil-finetune-v3" \
  --push_to_hub 1 \
  --hub_repo_id quyanh/qwen3-asr-tamil
```

### Logs

```shell
2026-02-13 09:24:53
  0%|                                                                                        | 0/8646 [00:00<?, ?it/s]`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
2026-02-13 09:25:07
Processing Files (6 / 6)      : 100%|████████████████████████████████████████████████████| 4.71GB / 4.71GB,  139MB/s  
2026-02-13 09:25:20
{'loss': 16.233, 'grad_norm': 374.0, 'learning_rate': 1.040462427745665e-06, 'epoch': 0.0}
2026-02-13 09:25:34
{'loss': 15.8321, 'grad_norm': 294.0, 'learning_rate': 2.1965317919075148e-06, 'epoch': 0.01}
2026-02-13 09:25:49
{'loss': 14.4195, 'grad_norm': 282.0, 'learning_rate': 3.3526011560693642e-06, 'epoch': 0.01}
2026-02-13 09:26:03
{'loss': 10.1926, 'grad_norm': 158.0, 'learning_rate': 4.508670520231214e-06, 'epoch': 0.01}
2026-02-13 09:26:18
{'loss': 8.0159, 'grad_norm': 123.5, 'learning_rate': 5.664739884393064e-06, 'epoch': 0.02}
2026-02-13 09:26:32
{'loss': 6.9161, 'grad_norm': 142.0, 'learning_rate': 6.820809248554914e-06, 'epoch': 0.02}
2026-02-13 09:26:46
{'loss': 6.174, 'grad_norm': 161.0, 'learning_rate': 7.976878612716764e-06, 'epoch': 0.02}
2026-02-13 09:27:01
{'loss': 5.6496, 'grad_norm': 127.5, 'learning_rate': 9.132947976878613e-06, 'epoch': 0.03}
2026-02-13 09:27:15
{'loss': 5.2912, 'grad_norm': 109.0, 'learning_rate': 1.0289017341040463e-05, 'epoch': 0.03}
2026-02-13 09:27:29
{'loss': 4.6653, 'grad_norm': 147.0, 'learning_rate': 1.1445086705202313e-05, 'epoch': 0.03}
2026-02-13 09:27:43
{'loss': 3.8658, 'grad_norm': 158.0, 'learning_rate': 1.2601156069364162e-05, 'epoch': 0.04}
2026-02-13 09:27:58
{'loss': 3.2473, 'grad_norm': 139.0, 'learning_rate': 1.3757225433526014e-05, 'epoch': 0.04}
2026-02-13 09:28:12
{'loss': 2.4114, 'grad_norm': 118.0, 'learning_rate': 1.4913294797687862e-05, 'epoch': 0.05}
2026-02-13 09:28:27
{'loss': 1.6319, 'grad_norm': 120.5, 'learning_rate': 1.606936416184971e-05, 'epoch': 0.05}
2026-02-13 09:28:42
{'loss': 1.0507, 'grad_norm': 57.75, 'learning_rate': 1.722543352601156e-05, 'epoch': 0.05}
2026-02-13 09:28:56
{'loss': 0.5709, 'grad_norm': 31.375, 'learning_rate': 1.838150289017341e-05, 'epoch': 0.06}
2026-02-13 09:29:11
{'loss': 0.3687, 'grad_norm': 15.125, 'learning_rate': 1.9537572254335264e-05, 'epoch': 0.06}
2026-02-13 09:29:25
{'loss': 0.3124, 'grad_norm': 10.25, 'learning_rate': 1.998583736575003e-05, 'epoch': 0.06}
2026-02-13 09:29:40
{'loss': 0.28, 'grad_norm': 10.6875, 'learning_rate': 1.996223297533341e-05, 'epoch': 0.07}
2026-02-13 09:29:57
{'loss': 0.385, 'grad_norm': 11.6875, 'learning_rate': 1.99386285849168e-05, 'epoch': 0.07}
2026-02-13 09:30:12
[hub] Uploading ./qwen3-asr-finetuning-out/checkpoint-200 → quyanh/qwen3-asr-tamil/checkpoint-200
2026-02-13 09:30:19
New Data Upload               : 100%|████████████████████████████████████████████████████| 5.84kB / 5.84kB,   584B/s  
2026-02-13 09:30:20
  ...eckpoint-200/scheduler.pt: 100%|████████████████████████████████████████████████████| 1.47kB / 1.47kB
2026-02-13 09:30:20
  ...ckpoint-200/rng_state.pth: 100%|████████████████████████████████████████████████████| 14.6kB / 14.6kB
2026-02-13 09:30:20
  ...kpoint-200/tokenizer.json: 100%|████████████████████████████████████████████████████| 11.4MB / 11.4MB
2026-02-13 09:30:20
  ...int-200/model.safetensors: 100%|████████████████████████████████████████████████████| 1.56GB / 1.56GB            
2026-02-13 09:30:20
  ...eckpoint-200/optimizer.pt: 100%|████████████████████████████████████████████████████| 3.13GB / 3.13GB            
2026-02-13 09:30:37
  ...int-200/training_args.bin: 100%|████████████████████████████████████████████████████| 5.84kB / 5.84kB
2026-02-13 09:30:41
  3%|██▎                                                                         | 266/8646 [07:24<3:23:37,  1.46s/it]Traceback (most recent call last):
2026-02-13 09:30:55
{'loss': 0.2435, 'grad_norm': 10.625, 'learning_rate': 1.9915024194500178e-05, 'epoch': 0.07}
2026-02-13 09:31:09
{'loss': 0.2435, 'grad_norm': 7.75, 'learning_rate': 1.989141980408356e-05, 'epoch': 0.08}
2026-02-13 09:31:24
{'loss': 0.2541, 'grad_norm': 11.5, 'learning_rate': 1.9867815413666945e-05, 'epoch': 0.08}
2026-02-13 09:31:39
{'loss': 0.2123, 'grad_norm': 7.75, 'learning_rate': 1.9844211023250325e-05, 'epoch': 0.08}
2026-02-13 09:31:54
{'loss': 0.2779, 'grad_norm': 6.71875, 'learning_rate': 1.9820606632833708e-05, 'epoch': 0.09}
2026-02-13 09:32:08
{'loss': 0.2012, 'grad_norm': 7.1875, 'learning_rate': 1.979700224241709e-05, 'epoch': 0.09}
2026-02-13 09:32:23
  File "/workspace/Qwen3-ASR/finetuning/qwen3_asr_sft.py", line 459, in <module>
2026-02-13 09:32:23
    main()
2026-02-13 09:32:23
  File "/workspace/Qwen3-ASR/finetuning/qwen3_asr_sft.py", line 455, in main
2026-02-13 09:32:23
    trainer.train()
2026-02-13 09:32:23
  File "/workspace/Qwen3-ASR/asr/lib/python3.11/site-packages/transformers/trainer.py", line 2325, in train
2026-02-13 09:32:23
    return inner_training_loop(
2026-02-13 09:32:23
           ^^^^^^^^^^^^^^^^^^^^
2026-02-13 09:32:23
  File "/workspace/Qwen3-ASR/asr/lib/python3.11/site-packages/transformers/trainer.py", line 2674, in _inner_training_loop
2026-02-13 09:32:23
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
2026-02-13 09:32:23
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-02-13 09:32:23
  File "/workspace/Qwen3-ASR/asr/lib/python3.11/site-packages/transformers/trainer.py", line 4020, in training_step
2026-02-13 09:32:23
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
2026-02-13 09:32:23
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-02-13 09:32:23
  File "/workspace/Qwen3-ASR/finetuning/qwen3_asr_sft.py", line 183, in compute_loss
2026-02-13 09:32:23
    outputs = model(**inputs)
2026-02-13 09:32:23
              ^^^^^^^^^^^^^^^
2026-02-13 09:32:23
  File "/workspace/Qwen3-ASR/asr/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl
2026-02-13 09:32:23
    return self._call_impl(*args, **kwargs)
2026-02-13 09:32:23
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-02-13 09:32:23
  File "/workspace/Qwen3-ASR/asr/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1787, in _call_impl
2026-02-13 09:32:23
    return forward_call(*args, **kwargs)
2026-02-13 09:32:23
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-02-13 09:32:23
  File "/workspace/Qwen3-ASR/asr/lib/python3.11/site-packages/accelerate/utils/operations.py", line 819, in forward
2026-02-13 09:32:23
    return model_forward(*args, **kwargs)
2026-02-13 09:32:23
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-02-13 09:32:23
  File "/workspace/Qwen3-ASR/asr/lib/python3.11/site-packages/accelerate/utils/operations.py", line 807, in __call__
2026-02-13 09:32:23
    return convert_to_fp32(self.model_forward(*args, **kwargs))
2026-02-13 09:32:23
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-02-13 09:32:23
  File "/workspace/Qwen3-ASR/asr/lib/python3.11/site-packages/accelerate/utils/operations.py", line 786, in convert_to_fp32
2026-02-13 09:32:23
    return recursively_apply(_convert_to_fp32, tensor, test_type=_is_fp16_bf16_tensor)
2026-02-13 09:32:23
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-02-13 09:32:23
  File "/workspace/Qwen3-ASR/asr/lib/python3.11/site-packages/accelerate/utils/operations.py", line 119, in recursively_apply
2026-02-13 09:32:23
    {
2026-02-13 09:32:23
  File "/workspace/Qwen3-ASR/asr/lib/python3.11/site-packages/accelerate/utils/operations.py", line 120, in <dictcomp>
2026-02-13 09:32:23
    k: recursively_apply(
2026-02-13 09:32:23
       ^^^^^^^^^^^^^^^^^^
2026-02-13 09:32:23
  File "/workspace/Qwen3-ASR/asr/lib/python3.11/site-packages/accelerate/utils/operations.py", line 127, in recursively_apply
2026-02-13 09:32:23
    return func(data, *args, **kwargs)
2026-02-13 09:32:23
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-02-13 09:32:23
  File "/workspace/Qwen3-ASR/asr/lib/python3.11/site-packages/accelerate/utils/operations.py", line 778, in _convert_to_fp32
2026-02-13 09:32:23
    return tensor.float()
2026-02-13 09:32:23
           ^^^^^^^^^^^^^^
2026-02-13 09:32:23
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 34.20 GiB. GPU 0 has a total capacity of 44.45 GiB of which 14.62 GiB is free. Process 1755159 has 29.82 GiB memory in use. Of the allocated memory 27.60 GiB is allocated by PyTorch, and 1.89 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

### Environment Information

```
wandb==0.24.2
sentry-sdk==2.52.0
protobuf==6.33.5
GitPython==3.1.46
gitdb==4.0.12
smmap==5.0.2
ninja==1.13.0
einops==0.8.2
setuptools==82.0.0
torch==2.10.0
transformers==4.57.6
sympy==1.14.0
scipy==1.17.0
pandas==3.0.0
nagisa==0.2.11
nvidia-nvjitlink-cu12==12.8.93
scikit-learn==1.8.0
gradio==6.5.1
numba==0.63.1
pillow==12.1.1
nvidia-curand-cu12==10.3.9.90
numpy==2.3.5
dyNET38==2.2
nvidia-cusparse-cu12==12.5.8.93
nvidia-cufft-cu12==11.3.3.83
llvmlite==0.46.0
nvidia-cusparselt-cu12==0.7.1
nvidia-nvshmem-cu12==3.4.5
nvidia-cudnn-cu12==9.10.2.21
pyarrow==23.0.0
nvidia-cusolver-cu12==11.7.3.90
pytz==2025.2
triton==3.6.0
Cython==3.2.4
nvidia-cublas-cu12==12.8.4.1
av==16.1.0
cuda-bindings==12.9.4
networkx==3.6.1
tokenizers==0.22.2
hf-xet==1.2.0
nvidia-nccl-cu12==2.27.5
Pygments==2.19.2
nvidia-cuda-nvrtc-cu12==12.8.93
nvidia-cuda-cupti-cu12==12.8.90
datasets==4.5.0
orjson==3.11.7
qwen-asr==0.0.6
httpx==0.28.1
charset-normalizer==3.4.4
packaging==26.0
dill==0.4.0
Werkzeug==3.1.5
frozenlist==1.8.0
annotated-doc==0.0.4
librosa==0.11.0
nvidia-cufile-cu12==1.13.1.3
shellingham==1.5.4
urllib3==2.6.3
psutil==7.2.2
certifi==2026.1.4
sox==1.5.0
fastapi==0.128.8
cffi==2.0.0
aiohttp==3.13.3
mdurl==0.1.2
huggingface_hub==0.36.2
blinker==1.9.0
multidict==6.7.1
ffmpy==1.0.0
Flask==3.1.2
qwen-omni-utils==0.0.9
xxhash==3.6.0
aiosignal==1.4.0
accelerate==1.12.0
propcache==0.4.1
decorator==5.2.1
joblib==1.5.3
safehttpx==0.1.7
soynlp==0.0.493
six==1.17.0
lazy_loader==0.4
groovy==0.1.2
anyio==4.12.1
annotated-types==0.7.0
aiofiles==24.1.0
typing-inspection==0.4.2
nvidia-cuda-runtime-cu12==12.8.90
aiohappyeyeballs==2.6.1
idna==3.11
mpmath==1.3.0
itsdangerous==2.2.0
requests==2.32.5
nvidia-nvtx-cu12==12.8.90
filelock==3.20.3
gradio_client==2.0.3
brotli==1.2.0
semantic-version==2.10.0
platformdirs==4.5.1
pooch==1.9.0
python-dateutil==2.9.0.post0
pycparser==3.0
click==8.3.1
audioread==3.1.0
starlette==0.52.1
markdown-it-py==4.0.0
rich==14.3.2
multiprocess==0.70.18
pydub==0.25.1
threadpoolctl==3.6.0
python-multipart==0.0.22
pydantic==2.12.5
typing_extensions==4.15.0
yarl==1.22.0
h11==0.16.0
Jinja2==3.1.6
pydantic_core==2.41.5
regex==2026.1.15
attrs==25.4.0
cuda-pathfinder==1.3.3
tqdm==4.67.3
PyYAML==6.0.3
fsspec==2025.10.0
MarkupSafe==3.0.3
tomlkit==0.13.3
uvicorn==0.40.0
msgpack==1.1.2
```

### Known Issue

- [x] The issue hasn't been already addressed in Documentation, Issues, and Discussions.

**Comment by almugabo** [comment]
did you find a solution to this ? does this happens also with higher VRAM ?

**Comment by JonathanMartel** [comment]
I have a similar problem. Try to transcribe 35 audio files from 60 to 90 minutes (interview). After 30 files I ran into OOM. This is not the longest file, the highest number of segment or words. I trace each memory allocation and I have always between 1,2 and 1,4Gb of free vram for each file (Run Qwen3-ASR with ForcedAlign, vllm set to use 0.65 % of vram on a A100:40Bg) I have torch.cuda.empty_cache() between each file and  PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

2026-02-23 00:38:21,972 | ERROR    |   : CUDA out of memory. Tried to allocate 19.92 GiB. GPU 0 has a total capacity of 39.49 GiB of which 7.46 GiB is free. Including non-PyTorch memory, this process has 5.00 GiB memory in use. Process 204415 has 27.02 GiB memory in use. Of the allocated memory 4.39 GiB is allocated by PyTorch, and 111.42 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 19.92 GiB. GPU 0 has a total capacity of 39.49 GiB of which 7.46 GiB is free. Including non-PyTorch memory, this process has 5.00 GiB memory in use. Process 204415 has 27.02 GiB memory in use. Of the allocated memory 4.39 GiB is allocated by PyTorch, and 111.42 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by QuyAnh2005** [comment]
@almugabo I resolved the issue by identifying anomalous samples in my training data, where the transcription did not match the audio and the transcript was excessively long (around 6000 characters). My training became more stable after removing these samples.

I recommend that everyone recheck their dataset

**Comment by AdilAdam** [comment]
you can write several line scripts in qwen3_asr_sft.py : DataCollatorForQwen3ASRFinetuning, and keep the input ids length within proper range， e.g. :

labels = full_inputs["input_ids"].clone()
labels_length = len(labels)    # or   labels.size(1)

if labels_length > 1024:
   continue

**Comment by WuZhongdi** [comment]
I added a truncation (by setting a truncation=True with max_length of 1024) in class DataCollatorForQwen3ASRFinetuning
and it worked for me, my speculation was some data in my dataset was long and without truncate the feature map was too big.
